# Copyright (c) Microsoft Corporation.
# Licensed under the MIT license.
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-kvname-win
spec:
  provider: azure
  secretObjects: # [OPTIONAL] SecretObject defines the desired state of synced K8s secret objects
    - data:
        - key: TICKET_DESK_SECURITY_CONNECTION_STRING
          objectName: TICKET_DESK_SECURITY_CONNECTION_STRING # name of the mounted content to sync. this could be the object name or object alias
        - key: TICKET_DESK_ENTITIES
          objectName: TICKET_DESK_ENTITIES
        - key: ELMAH_LOG
          objectName: ELMAH_LOG
      secretName: akvsecretscertwin
      type: Opaque

  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "<Client Id>" # Provide your cluster managed identity's clientId you can find it on azure portal
    keyvaultName: <keyvault name> # The name of the KeyVault
    cloudName: AzurePublicCloud # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects:  |
      array:
        - |
          objectName: TicketDeskSecurityConnectionString
          objectAlias: TICKET_DESK_SECURITY_CONNECTION_STRING
          objectType: secret
          objectVersion: ""
        - |
          objectName: TicketDeskEntities
          objectAlias: TICKET_DESK_ENTITIES
          objectType: secret
          objectVersion: ""
        - |
          objectName: ElmahLog
          objectAlias: ELMAH_LOG
          objectType: secret
          objectVersion: ""

    resourceGroup: "<Resource group>" # Provide azure key vault resourceGroup
    subscriptionId: "<Subscription Id>" # subscriptionId
    tenantId: "<Tenant Id>" # TenantId
